ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/yangarse/application'
  tag: 'chart_v1'

service:
  servicePort: 8080

probes:
  readiness:
    path: '/health/readiness'
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3